### ISSUE TITLE
内网穿透 client 端通过内网代理连接 bridge 出错

### ISSUE THREAD

**Issue by streamone** [snail007/goproxy#164]
6.3版做内网穿透，client 端通过内网代理连接 bridge，配置需要密码认证的代理时运行抛出大量错误，无法连接 bridge端，配置不需要密码认证的代理时启动后也抛出同样的错误，但是过一会儿就可以连接了，日志输出也正常了。

错误信息如下：
```
C:\proxy-windows-amd64>proxy.exe @client_config.txt
Proxy Enterprise Version v6.3_20181015123005 by snail , blog : http://www.host900.com/

2018/10/25 15:46:09 client started
2018/10/25 15:46:09 session worker[1] started
2018/10/25 15:46:09 session worker[2] started
2018/10/25 15:46:09 session worker[3] started
2018/10/25 15:46:09 session worker[4] started
2018/10/25 15:46:09 session worker[5] started
2018/10/25 15:46:09 session worker[6] started
2018/10/25 15:46:09 session worker[7] started
2018/10/25 15:46:09 session worker[8] started
2018/10/25 15:46:09 session worker[9] started
2018/10/25 15:46:09 session worker[10] started
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 11 [running]:
runtime/debug.Stack(0xc0422f3dd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc042017680, 0x9, 0x4)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 16 [running]:
runtime/debug.Stack(0xc0422d1dd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc042017700, 0x9, 0x9)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 15 [running]:
runtime/debug.Stack(0xc0422c9dd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc0420176e0, 0x9, 0x8)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 8 [running]:
runtime/debug.Stack(0xc04224bdd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc042017640, 0x9, 0x1)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 9 [running]:
runtime/debug.Stack(0xc042243dd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc042017650, 0x9, 0x2)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 14 [running]:
runtime/debug.Stack(0xc0422fddd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc0420176d0, 0x9, 0x7)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 33 [running]:
runtime/debug.Stack(0xc0422ebdd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc042017710, 0xa, 0xa)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 13 [running]:
runtime/debug.Stack(0xc0422addd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc0420176b0, 0x9, 0x6)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:09 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 10 [running]:
runtime/debug.Stack(0xc0422c1dd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc042017670, 0x9, 0x3)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
2018/10/25 15:46:10 session worker crashed: runtime error: invalid memory address or nil pointer dereference
stack:goroutine 12 [running]:
runtime/debug.Stack(0xc04227ddd8, 0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xae
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1.1(0xc042034d80)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:149 +0x61
panic(0x9a8d20, 0xe28090)
        /usr/local/go/src/runtime/panic.go:502 +0x237
github.com/snail007/goproxy/services/mux.(*MuxClient).Start.func1(0xc042034d80, 0xc0420176a0, 0x9, 0x5)
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:162 +0x19c
created by github.com/snail007/goproxy/services/mux.(*MuxClient).Start
        /home/pengmeng/go/src/github.com/snail007/goproxy/services/mux/mux_client.go:145 +0x309
```

**Comment by streamone** [comment]
client配置文件如下：

```
client
--k=test
--parent=x.x.x.x:xxxx
--cert=proxy.crt
--key=proxy.key
--jumper=https://user:password@proxy:8080
```
