### ISSUE TITLE
[bug]v8.2 p2p tools

### ISSUE THREAD

**Issue by pinghe** [snail007/goproxy#317]
在内网运行 ./proxy tools -a nattype  报错
```
proxy free version 8.2  by snail , email : arraykeys@gmail.com
checking if your network is p2p supported, maybe need a minute.
Stun Server :  stun.fbsbx.com:3478
Nat Type :  UDP is blocked
2019/09/18 15:39:26 err : run service [tools:tools] fail, ERR:tools servcie crashed, ERR: runtime error: invalid memory address or nil pointer dereference
trace:goroutine 1 [running]:
runtime/debug.Stack(0xc420220170, 0xaa0540, 0xfee290)
	/usr/local/go1.10.1/src/runtime/debug/stack.go:24 +0xa7
github.com/snail007/proxy/services.Run.func1(0x7fff20915f29, 0x5, 0xc4202204c0)
	/Users/go/src/github.com/snail007/proxy/services/service.go:80 +0x88
panic(0xaa0540, 0xfee290)
	/usr/local/go1.10.1/src/runtime/panic.go:502 +0x229
github.com/snail007/proxy/core/stun.(*Host).IP(...)
	/Users/go/src/github.com/snail007/proxy/core/stun/host.go:54
github.com/snail007/proxy/services/tools.(*Tools).Start(0xc420242200, 0xab3fe0, 0xc420233450, 0xc420095090, 0xc4202204c0, 0xa6cc01)
	/Users/go/src/github.com/snail007/proxy/services/tools/tools.go:72 +0x36a
github.com/snail007/proxy/services.Run(0x7fff20915f29, 0x5, 0x0, 0x0, 0xc42023e6c0, 0x0, 0x0)
	/Users/go/src/github.com/snail007/proxy/services/service.go:87 +0x2b3
github.com/snail007/proxy/core/runner.StartWithLog(0x7fff20915f29, 0x5, 0xc420029010, 0x10, 0x0, 0x0, 0xc420094be0, 0xe6bd4452e80, 0xc420094be0)
	/Users/go/src/github.com/snail007/proxy/core/runner/runner.go:773 +0x1f8fd
github.com/snail007/proxy/core/runner.Start(0x7fff20915f29, 0x5, 0xc420029010, 0x10, 0x1, 0xc420029010, 0x10)
	/Users/go/src/github.com/snail007/proxy/core/runner/runner.go:72 +0x51
main.main()
	proxy/main.go:72 +0xab

```

不支持 --jumper http://myproxy:port

**Comment by snail007** [comment]
报错已经修复，--jumper 只适用于 有这个参数的功能。
